name: build
on: [push, pull_request]

jobs:
  lint-k8s:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://golangci/golangci-lint:v1.31.0
      with:
        args: golangci-lint run
      env:
        CGO_ENABLED: 0
      working-directory: k8s
  test-k8s:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - name: Run Unit tests
      run: go test -covermode atomic -coverprofile=profile.cov $(go list -m)/...
        working-directory: k8s
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        GO111MODULE=off go get github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
  lint-k8s:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://golangci/golangci-lint:v1.31.0
      with:
        args: golangci-lint run
      env:
        CGO_ENABLED: 0
      working-directory: kv
  test-kv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - name: Run Unit tests
      run: go test -covermode atomic -coverprofile=profile.cov $(go list -m)/...
        working-directory: kv
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        GO111MODULE=off go get github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github

